import { useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Activity, CalendarDays, Check, ChevronRight, CircleHelp, Flame, History, Home, Leaf, Moon, Plus, Search, Settings, Sparkles, Sun, Target, Trash2, X } from 'lucide-react'
import { checklistLabels } from './data'
import { createRemote, deleteRemote, fetchPublishedSheet, fetchRemoteEntries, hasRemoteApi, updateRemote } from './api'
import { formatCount, formatDate, getCount, getStreak, readSettings, saveSettings, sum, today } from './lib'
import type { Checklist, JapaEntry, Settings as AppSettings } from './types'

const card = 'rounded-[24px] border border-[#eadfd1] bg-white/75 shadow-[0_16px_45px_rgba(83,58,37,0.06)] backdrop-blur-sm dark:border-white/10 dark:bg-white/[0.06]'
const emptyChecklist = (): Checklist => ({ mantra: false, sahasranama: false, astottaranama: false, kavacham: false, panjaram: false, archana: false })
const uid = () => crypto.randomUUID?.() ?? `${Date.now()}-${Math.random()}`

function App() {
  const [entries, setEntries] = useState<JapaEntry[]>([])
  const [settings, setSettings] = useState<AppSettings>(readSettings)
  const [tab, setTab] = useState('Overview'); const [modal, setModal] = useState<JapaEntry | true | null>(null)
  const [dark, setDark] = useState(settings.theme === 'dark'); const [sync, setSync] = useState('local')
  useEffect(() => { document.documentElement.classList.toggle('dark', dark) }, [dark])
  const refresh = () => { setSync('syncing'); const request = hasRemoteApi ? fetchRemoteEntries() : fetchPublishedSheet(); request.then(remote => { setEntries(remote || []); setSync(hasRemoteApi ? 'synced' : 'sheet-read') }).catch(() => setSync('offline')) }
  useEffect(() => { refresh(); const interval = window.setInterval(refresh, 30000); return () => window.clearInterval(interval) }, [])
  const save = (next: JapaEntry[]) => setEntries(next)
  const remote = (action: Promise<void>) => { setSync('syncing'); action.then(() => setSync('synced')).catch(() => setSync('offline')) }
  const requireWriteApi = () => { if (hasRemoteApi) return true; alert('One-time setup required: deploy apps-script/Code.gs from Google Sheets, copy the Web App URL, and paste it into appsScriptEndpoint in src/api.ts.'); return false }
  const add = (input: Partial<JapaEntry>) => { if (!requireWriteApi()) return; const now = new Date().toISOString(); const count = Math.max(0, Math.floor(input.japa_count || 0)); const entry: JapaEntry = { id: uid(), date: input.date || today(), japa_count: count, checklist: input.checklist || emptyChecklist(), description: input.description || 'Entry', total_count: count, duration_min: 0, notes: '', created_at: now, updated_at: now }; save([entry, ...entries]); remote(createRemote(entry)); setModal(null) }
  const update = (input: JapaEntry) => { if (!requireWriteApi()) return; const next = { ...input, japa_count: Math.max(0, Math.floor(input.japa_count || 0)), total_count: Math.max(0, Math.floor(input.japa_count || 0)), updated_at: new Date().toISOString() }; save(entries.map(entry => entry.id === next.id ? next : entry)); remote(updateRemote(next)); setModal(null) }
  const remove = (id: string) => { if (!requireWriteApi()) return; if (!confirm('Remove this day from your practice history?')) return; save(entries.filter(entry => entry.id !== id)); remote(deleteRemote(id)) }
  const current = entries.filter(entry => entry.date === today()); const lifetime = sum(entries); const streak = getStreak(entries)
  return <div className="min-h-screen bg-[#f7f3eb] text-[#312b29] dark:bg-[#19171c] dark:text-[#f8f1e7]">
    <aside><Brand /><Nav current={tab} onChange={setTab} /><div className="help-card"><CircleHelp size={17} /><b>Keep it simple</b><p>One sincere offering is enough for today.</p></div></aside>
    <main><header><div className="mobile-brand"><Brand compact /></div><div className="date-label">{new Intl.DateTimeFormat('en', { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date())}</div><div className="header-actions"><button className="icon-button" onClick={() => { setDark(!dark); setSettings({ ...settings, theme: dark ? 'light' : 'dark' }) }}>{dark ? <Sun size={18} /> : <Moon size={18} />}</button><div className="avatar">AS</div></div></header>
      {tab === 'Overview' && <Overview entries={entries} current={current} lifetime={lifetime} streak={streak.current} goal={settings.dailyGoal} sync={sync} onAdd={() => setModal(true)} onRefresh={refresh} />}
      {tab === 'History' && <HistoryView entries={entries} onAdd={() => setModal(true)} onEdit={setModal} onDelete={remove} />}
      {tab === 'Practice' && <Practice entries={current} goal={settings.dailyGoal} onSave={add} />}
      {tab === 'Settings' && <SettingsView settings={settings} update={next => { setSettings(next); saveSettings(next) }} />}
    </main><nav className="bottom-nav"><Nav current={tab} onChange={setTab} mobile /></nav>
    <AnimatePresence>{modal && <EntryModal initial={modal === true ? undefined : modal} onClose={() => setModal(null)} onSave={modal === true ? add : entry => update(entry as JapaEntry)} />}</AnimatePresence>
  </div>
}

function Brand({ compact = false }: { compact?: boolean }) { return <div className="brand"><div className="brand-mark"><Leaf size={20} /></div>{!compact && <div><div className="brand-name">Japa Sadhana</div><div className="brand-sub">Daily devotion</div></div>}</div> }
function Nav({ current, onChange, mobile = false }: { current: string; onChange: (value: string) => void; mobile?: boolean }) { const items = [[Home, 'Overview'], [Activity, 'Practice'], [History, 'History'], [Settings, 'Settings']] as const; return <div className={`nav ${mobile ? 'mobile-nav' : ''}`}>{items.map(([Icon, label]) => <button className={current === label ? 'active' : ''} onClick={() => onChange(label)} key={label}><Icon size={18} /><span>{label}</span></button>)}</div> }

function Overview({ entries, current, lifetime, streak, goal, sync, onAdd, onRefresh }: { entries: JapaEntry[]; current: JapaEntry[]; lifetime: number; streak: number; goal: number; sync: string; onAdd: () => void; onRefresh: () => void }) { const todayCount = sum(current); const chart = useMemo(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - 6 + index); const key = date.toISOString().slice(0, 10); return { day: date.toLocaleDateString('en', { weekday: 'short' }), count: sum(entries.filter(entry => entry.date === key)) } }), [entries]); const done = current.reduce((total, entry) => total + Object.values(entry.checklist || emptyChecklist()).filter(Boolean).length, 0); const latest = [...entries].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 5); return <>
  <section className="hero"><div><div className="eyebrow"><Sparkles size={14} /> DAILY SADHANA <span className="sync-pill">{sync === 'sheet-read' ? 'Sheet connected' : sync}</span></div><h1>Welcome back, <em>Arjun.</em></h1><p>Keep the count. Keep the connection.</p></div><div className="hero-actions"><button className="secondary-button" onClick={onRefresh}>Refresh sheet</button><button className="primary-button" onClick={onAdd}><Plus size={18} /> Add today</button></div></section>
  <div className="stats-grid"><Stat icon={Target} label="Today's japa" value={formatCount(todayCount)} sub={`of ${formatCount(goal)} goal`} /><Stat icon={Flame} label="Current streak" value={streak} sub="days in a row" /><Stat icon={CalendarDays} label="Checklist" value={`${done}/6`} sub="completed today" /><Stat icon={Activity} label="Lifetime japa" value={formatCount(lifetime)} sub="total count" /></div>
  <div className="dashboard-grid"><section className={`${card} panel chart-panel`}><div className="panel-heading"><div><h2>Japa rhythm</h2><p className="muted">Your count for the last seven days</p></div><span className="count-badge">{formatCount(lifetime)} total</span></div><div className="chart-box"><ResponsiveContainer><AreaChart data={chart}><defs><linearGradient id="japaFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#d87a4d" stopOpacity={.32} /><stop offset="100%" stopColor="#d87a4d" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#eee5dc" /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: '#a39890', fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#a39890', fontSize: 11 }} width={35} /><Tooltip contentStyle={{ borderRadius: 14, border: '1px solid #eadfd1' }} /><Area type="monotone" dataKey="count" stroke="#c86e48" strokeWidth={3} fill="url(#japaFill)" /></AreaChart></ResponsiveContainer></div></section><section className={`${card} panel offering-panel`}><div className="panel-heading"><div><h2>Today's checklist</h2><p className="muted">Mark each practice as you finish</p></div><span className="om">ॐ</span></div>{checklistLabels.map(([key, label]) => <div className="check-row" key={key}><span>{label}</span><span className={current.some(entry => entry.checklist?.[key]) ? 'check done' : 'check'}>{current.some(entry => entry.checklist?.[key]) && <Check size={14} />}</span></div>)}<button className="secondary-button full" onClick={onAdd}>Update today <ChevronRight size={16} /></button></section></div>
  <section className={`${card} panel recent-panel`}><div className="panel-heading"><div><h2>Recent days</h2><p className="muted">Your recorded offerings</p></div></div>{latest.map(entry => <div className="history-row" key={entry.id}><div className="entry-icon">ॐ</div><div className="min-w-0 flex-1"><b>{entry.description || 'Japa'}</b><div className="muted text-xs">{formatDate(entry.date)} · {Object.values(entry.checklist || emptyChecklist()).filter(Boolean).length}/6 practices</div></div><strong className="count-value">{formatCount(getCount(entry))}</strong></div>)}</section></> }
function Stat({ icon: Icon, label, value, sub }: { icon: typeof Target; label: string; value: string | number; sub: string }) { return <div className={`${card} stat-card`}><div className="stat-icon orange"><Icon size={18} /></div><div><p className="muted text-xs">{label}</p><strong>{value}</strong><small>{sub}</small></div></div> }

function HistoryView({ entries, onAdd, onEdit, onDelete }: { entries: JapaEntry[]; onAdd: () => void; onEdit: (entry: JapaEntry) => void; onDelete: (id: string) => void }) { const [search, setSearch] = useState(''); const rows = entries.filter(entry => `${entry.date} ${entry.description || ''}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.date.localeCompare(a.date)); return <><section className="hero"><div><div className="eyebrow"><History size={14} /> YOUR RECORD</div><h1>Every day <em>counts.</em></h1><p>Review your japa and daily practices.</p></div><button className="primary-button" onClick={onAdd}><Plus size={18} /> Add entry</button></section><section className={`${card} panel`}><div className="panel-heading history-heading"><div><h2>Practice history</h2><p className="muted">{entries.length} recorded days</p></div><div className="search"><Search size={16} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search date or description" /></div></div>{rows.map(entry => <div className="history-row large" key={entry.id}><div className="entry-icon">ॐ</div><div className="min-w-0 flex-1"><b>{entry.description || 'Japa'}</b><div className="muted text-xs">{formatDate(entry.date)} · {Object.values(entry.checklist || emptyChecklist()).filter(Boolean).length}/6 checklist items</div></div><strong className="count-value">{formatCount(getCount(entry))}</strong><button className="icon-button small" onClick={() => onEdit(entry)}>Edit</button><button className="icon-button small danger" onClick={() => onDelete(entry.id)}><Trash2 size={15} /></button></div>)}</section></> }

function Practice({ entries, goal, onSave }: { entries: JapaEntry[]; goal: number; onSave: (entry: Partial<JapaEntry>) => void }) { const [count, setCount] = useState(0); const total = sum(entries) + count; return <><section className="hero"><div><div className="eyebrow"><Activity size={14} /> LIVE JAPA COUNT</div><h1>One count at a <em>time.</em></h1><p>Record the number of chants you completed.</p></div><button className="primary-button" disabled={!count} onClick={() => onSave({ date: today(), japa_count: count, checklist: emptyChecklist(), description: 'Japa' })}>Save count</button></section><section className={`${card} counter-panel`}><div className="count-orb"><strong>{formatCount(count)}</strong><span>japa count</span></div><div className="counter-actions"><button onClick={() => setCount(Math.max(0, count - 1))}>−</button><button onClick={() => setCount(count + 1)}>+1 count</button></div><p className="muted">Today: {formatCount(total)} · Goal: {formatCount(goal)}</p></section></> }

function EntryModal({ initial, onClose, onSave }: { initial?: JapaEntry; onClose: () => void; onSave: (entry: Partial<JapaEntry> | JapaEntry) => void }) { const [date, setDate] = useState(initial?.date || today()); const [count, setCount] = useState(initial ? getCount(initial) : 0); const [description, setDescription] = useState(initial?.description || 'Entry'); const [checklist, setChecklist] = useState<Checklist>(initial?.checklist || emptyChecklist()); const toggle = (key: keyof Checklist) => setChecklist(current => ({ ...current, [key]: !current[key] })); return <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}><motion.div className="modal" initial={{ y: 24, opacity: 0 }} animate={{ y: 0, opacity: 1 }} onClick={event => event.stopPropagation()}><div className="modal-title"><div><div className="eyebrow"><Sparkles size={14} /> DAILY ENTRY</div><h2>{initial ? 'Edit this day' : 'Add practice'}</h2></div><button className="icon-button" onClick={onClose}><X size={18} /></button></div><label>Date<input type="date" value={date} onChange={event => setDate(event.target.value)} /></label><label>Description <span>(optional)</span><input value={description} onChange={event => setDescription(event.target.value)} placeholder="Entry or D1" /></label><label>Japa count<input type="number" min="0" value={count} onChange={event => setCount(Math.max(0, Number(event.target.value)))} /></label><div className="checklist-editor"><p>Daily practices</p>{checklistLabels.map(([key, label]) => <button className={checklist[key] ? 'checked' : ''} key={key} onClick={() => toggle(key)}><span>{checklist[key] ? <Check size={15} /> : null}</span>{label}</button>)}</div><div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" onClick={() => onSave(initial ? { ...initial, date, japa_count: count, total_count: count, description, checklist } : { date, japa_count: count, description, checklist })}>{initial ? 'Update day' : 'Save day'}</button></div></motion.div></motion.div> }

function SettingsView({ settings, update }: { settings: AppSettings; update: (settings: AppSettings) => void }) { return <><section className="hero"><div><div className="eyebrow"><Settings size={14} /> PERSONAL RHYTHM</div><h1>Your <em>settings.</em></h1><p>Keep your daily target gentle and clear.</p></div></section><section className={`${card} panel settings-panel`}><h2>Daily japa goal</h2><p className="muted">The goal is a guide, not a judgment.</p><label>Count goal<input type="number" min="1" value={settings.dailyGoal} onChange={event => update({ ...settings, dailyGoal: Math.max(1, Number(event.target.value)) })} /></label></section></> }
export default App
